### ISSUE TITLE
validateSchema option causes error

### ISSUE THREAD

**Issue by larshalvorsen** [EHDEN/CatalogueExport#17]
**Describe the bug**
Setting the parameter validateSchema to TRUE causes an error:
```Error:
org.postgresql.util.PSQLException: ERROR: column "qualifier_source_value" does not exist
  Position: 5822
```
Looking at the error log, it expects to find this field in the `procedure_occurrence` table - there is no such field in this table.
[errorReportSql.txt](https://github.com/EHDEN/CatalogueExport/files/5777677/errorReportSql.txt)

**To Reproduce**
Set the parameter `validateSchema = TRUE` in the catalogueExport function call.

**Comment by PRijnbeek** [comment]
I decided to remove this option.
