### ISSUE TITLE
java.sql.SQLException: Invalid SQL type: sqlKind = UNINITIALIZED

### ISSUE THREAD

**Issue by scossin** [EHDEN/CatalogueExport#19]
**Describe the bug**
When executing analysis id 0 and 5000, we encountered a "java.sql.SQLException: Invalid SQL type: sqlKind = UNINITIALIZED" error. Our DBMS is Oracle. 

I don't really understand why this error appears but it disappears if we add a space between -- and HINT in these two files: 
https://github.com/EHDEN/CatalogueExport/blob/a7cdbd86e916e43ba1b67714236fc1eaf57b6320/inst/sql/sql_server/analyses/0.sql#L11
https://github.com/EHDEN/CatalogueExport/blob/a7cdbd86e916e43ba1b67714236fc1eaf57b6320/inst/sql/sql_server/analyses/5000.sql#L13

**To Reproduce**
The error occurs when running CatalogueExport::catalogueExport() function

**Comment by PRijnbeek** [comment]
Ok strange, thanks for fixing this.
