### ISSUE TITLE
.getSourceName called but its result is not assigned

### ISSUE THREAD

**Issue by scossin** [EHDEN/CatalogueExport#21]
**Describe the bug**
The bug is about the parameter sourceName (_String name of the data source name. If blank, CDM_SOURCE table will be queried to try to obtain this_). 
If sourceName is not given as parameter to the CatalogueExport::catalogueExport() function, .getSourceName is called to retrieve its value but the value it returns is not set to a variable so sourceName remains empty. 
https://github.com/EHDEN/CatalogueExport/blob/a7cdbd86e916e43ba1b67714236fc1eaf57b6320/R/CatalogueExport.R#L145

**To Reproduce**
Call CatalogueExport::catalogueExport() function without sourceName parameter

**Expected behavior**
```R
  if (missing(sourceName) & !sqlOnly) {
sourceName <- .getSourceName(connectionDetails, cdmDatabaseSchema) 
  }
```

**Comment by PRijnbeek** [comment]
Thanks agreed.

**Comment by PRijnbeek** [comment]
Can you make a pull request for this fix

**Comment by PRijnbeek** [comment]
will be close when merged in Master
