### ISSUE TITLE
Incorrect Syntax Near ')'

### ISSUE THREAD

**Issue by ericaVoss** [EHDEN/CatalogueExport#30]
**Describe the bug**
When Praveen is fully specifying the catalogueExport() function it is throwing an error

**To Reproduce**
![image](https://user-images.githubusercontent.com/6305439/108600874-7e234b00-7367-11eb-8be2-6982a34f27a9.png)

**Expected behavior**
Generates proper SQL

**Screenshots**
![image](https://user-images.githubusercontent.com/6305439/108399501-2d391880-71e8-11eb-95a1-7e83ecedc659.png)

I'm guessing because he is throwing in an empty object, the SQL isn't building right:
https://github.com/EHDEN/CatalogueExport/blob/f81edcd7510add2789bb4cb33beaefe2e84eebb1/inst/sql/sql_server/analyses/create_analysis_table.sql#L7

![image](https://user-images.githubusercontent.com/6305439/108399857-9456cd00-71e8-11eb-9855-53798601984b.png)

**Additional context**
@PRijnbeek - I'm sure this isn't a bug, just maybe we are calling the function incorrectly

**Comment by PRijnbeek** [comment]
There is a ) at the beginning of the line of dropScratchTables the comma before that it will not like.

This is not a bug

**Comment by ericaVoss** [comment]
Agreed, closing
