### ISSUE TITLE
Error in executing CatalogueExport on Postgre CDM 5.3.1

### ISSUE THREAD

**Issue by paix30** [EHDEN/CatalogueExport#32]
Dear Peter,
I can run CDMInspection, ACCHILLES, DQD but when I run the following code I get the error below. Appreciate your support.

if (!require("devtools")) install.packages("devtools")
# To install the master branch
devtools::install_github("EHDEN/CatalogueExport")
library(rJava)
library(DatabaseConnector)
library(SqlRender)
library(ParallelLogger) 
library(CatalogueExport)
Sys.setenv(DATABASECONNECTOR_JAR_FOLDER="C:/Users/brerd/Documents/R/win-library/4.0/DatabaseConnector/java")
connectionDetails <- createConnectionDetails(dbms = "postgresql", server = "10.1.0.193/ehden", user = "xxx", password = "XXX", port="5432")
catalogueExport(connectionDetails,
                cdmDatabaseSchema = "public", 
                resultsDatabaseSchema="results",
                vocabDatabaseSchema = "public",
                numThreads = 1,
                createTable = TRUE,
                sqlOnly=TRUE,
                verboseMode=TRUE)

ERROR:
Error in paste0("Running on server: ", connectionDetails$server, " on schema ",  : 
  cannot coerce type 'closure' to vector of type 'character'

**Comment by PRijnbeek** [comment]
Are you following these instructions: https://github.com/EHDEN/CatalogueExport/blob/master/extras/CodeToRun.R ?

**Comment by paix30** [comment]
Hi Peter, I followed the instructions from the beginning once more but still getting the same error. I tried both on the CDM server and on a client laptop. 

I changed the connection detail with pathToDriver parameter as below. 
connectionDetails <- DatabaseConnector::createConnectionDetails(dbms = "postgresql", user = "postgres", 
                                                                password = "ehden", server = "10.1.0.193/ehden", 
                                                                port = "5432", pathToDriver = "C:/Users/brerd/Documents/R/win-library/4.0/DatabaseConnectorJars/java")

I tried running catalogueExport without even setting connectionDetails and recieved the same error. From my understanding it gives the errror before creating a DB connection. Anythig else you advise me to check?

**Comment by PRijnbeek** [comment]
https://github.com/EHDEN/CatalogueExport/blob/20d6a3a16b46628463923062d926565813dfa577/R/CatalogueExport.R#L111

It is due to a recent change in DatabaseConnector the connectionDetails$server does not work anymore and now should be server() will fix it and update version.

**Comment by filipmaljkovic** [comment]
I got the same problem on server, but everything works fine client-side. I would be grateful if we could get this in the codebase soon. :)

**Comment by paix30** [comment]
Hi @filipmaljkovic, 
I downloaded the master code, deleted the problematic line, and executed it.
All worked fine.
